### ISSUE TITLE
Debug ROS2 integration + Test with Base Station

### ISSUE THREAD

**Issue by sah4jpatel** [SWAMP-Blimps/CatchingBlimp#27]
<someone fill this in with relevant details>

**Comment by sah4jpatel** [comment]
any updates to add here @Vishnav03  @tenyoku345 @ndickey3 ?

**Comment by Vishnav03** [comment]
ROS2 integration is complete, we've successfully tested it with the base station and manual control works with the xbox controller. Next steps include finding a way to get gpio access without having to be super user, Willie found this that we can make use of: https://github.com/awesometic/WiringPi-gpiod which has non su access to gpio pins but for odrioid, but can be used for WiringPi

**Comment by Vishnav03** [comment]
ROS2 integration is complete, we've successfully tested it with the base station and manual control works with the xbox controller. Next steps include finding a way to get gpio access without having to be super user, Willie found this that we can make use of: https://github.com/awesometic/WiringPi-gpiod which has non su access to gpio pins but for odrioid, but can be used for WiringPi
